name = "OscarBookExamples"
uuid = "e70fc62a-913c-41d4-837d-eaf0e8577d7a"
authors = ["Lars Kastner <lars.kastner@posteo.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"
Oscar = "~1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
